# Generated by Django 4.1.7 on 2023-02-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='hire datetime')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.job')),
            ],
        ),
    ]
