# Generated by Django 4.1.7 on 2023-02-22 15:49
import csv
import os
import logging

from django.db import migrations, transaction
from django.db.utils import IntegrityError
from django.core.exceptions import ValidationError

dirname = os.path.dirname(__file__)
data_dir = os.path.join(dirname, 'initial_data')


def load_csv_data(apps, schema_editor):

    Job = apps.get_model('employees', 'Job')
    Department = apps.get_model('employees', 'Department')
    Employee = apps.get_model('employees', 'Employee')

    with open(os.path.join(data_dir, 'jobs.csv')) as csvfile:
        csvreader = csv.DictReader(csvfile, fieldnames=["id", "job"])
        for row in csvreader:
            try:
                Job.objects.create(**row)
            except IntegrityError as e:
                logging.error('Error inserting: %s', row["id"])

    with open(os.path.join(data_dir, 'departments.csv')) as csvfile:
        csvreader = csv.DictReader(csvfile, fieldnames=["id", "department"])
        for row in csvreader:
            try:
                Department.objects.create(**row)
            except IntegrityError as e:
                logging.error('Error inserting: %s', row["id"])

    with open(os.path.join(data_dir, 'hired_employees.csv')) as csvfile:
        csvreader = csv.DictReader(
            csvfile,
            fieldnames=["id", "name", "datetime", "department_id", "job_id"])
        for row in csvreader:
            try:
                row["department"] = Department.objects.get(
                    pk=row.pop("department_id"))
                row["job"] = Job.objects.get(pk=row.pop("job_id"))
                with transaction.atomic():
                    Employee.objects.create(**row)
            except (IntegrityError, ValueError, ValidationError) as e:
                logging.error('Error inserting: %s', row["id"])
                logging.error(row)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_csv_data),
    ]
